src/Entity/Course.php
<?php

namespace App\Entity;

use App\Repository\CourseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: CourseRepository::class)]
#[Vich\Uploadable]
class Course
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(
        message: 'Le nom ne peux pas être vide.',
    )]
    #[Assert\Length(
        min: 3,
        max: 120,
        minMessage: 'Le nom doit contenir au moins {{ limit }} caractères.',
        maxMessage: 'Le nom ne doit pas dépasser {{ limit }} caractères.',
    )]
    #[ORM\Column(length: 120, nullable: true)]
    private ?string $name = null;

    #[Assert\NotBlank(
        message: 'La petite description ne peux pas être vide.',
    )]
    #[Assert\Length(
        min: 10,
        minMessage: 'Le petite description doit contenir au moins {{ limit }} caractères.',
    )]
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $small_description = null;

    #[Assert\NotBlank(
        message: 'La full description ne peux pas être vide.',
    )]
    #[Assert\Length(
        min: 10,
        minMessage: 'La full description doit contenir au moins {{ limit }} caractères.',
    )]
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $full_description = null;

    #[Assert\NotBlank(
        message: '',
    )]
    #[ORM\Column(length: 60, nullable: true)]
    private ?string $duration = null;

    #[Assert\NotBlank(
        message: '',
    )]
    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?bool $is_published = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[Vich\UploadableField(mapping: 'courseImage', fileNameProperty: 'image')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[Vich\UploadableField(mapping: 'pdf', fileNameProperty: 'program')]
    private ?File $pdfFile = null;
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $program = null;

    #[ORM\ManyToOne(inversedBy: 'courses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'courses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Level $level = null;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'course', cascade: ['remove'])]
    private Collection $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSmallDescription(): ?string
    {
        return $this->small_description;
    }

    public function setSmallDescription(string $small_description): static
    {
        $this->small_description = $small_description;

        return $this;
    }

    public function getFullDescription(): ?string
    {
        return $this->full_description;
    }

    public function setFullDescription(string $full_description): static
    {
        $this->full_description = $full_description;

        return $this;
    }

    public function getDuration(): ?string
    {
        return $this->duration;
    }

    public function setDuration(string $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setPublished(bool $is_published): static
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getProgram(): ?string
    {
        return $this->program;
    }

    public function setProgram(?string $program): static
    {
        $this->program = $program;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getLevel(): ?Level
    {
        return $this->level;
    }

    public function setLevel(?Level $level): static
    {
        $this->level = $level;

        return $this;
    }

    // vich pour l'image
    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    // Vich pour le pdf
    public function setPdfFile(?File $pdfFile = null): void
    {
        $this->pdfFile = $pdfFile;
        if (null !== $pdfFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }
    public function getPdfFile(): ?File
    {
        return $this->pdfFile;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setCourse($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getCourse() === $this) {
                $comment->setCourse(null);
            }
        }

        return $this;
    }
}

src/Form/CourseType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Course;
use App\Entity\Level;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Vich\UploaderBundle\Form\Type\VichFileType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class CourseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom',
            ])
            ->add('small_description', TextareaType::class, [
                'label' => 'Petite description',
            ])
            ->add('full_description', TextareaType::class, [
                'label' => 'Description',
            ])
            ->add('duration', TextType::class, [
                'label' => 'Durée'
            ])
            ->add('price', NumberType::class, [
                'label' => 'Prix',
                'scale' => 2
            ] )
//            ->add('created_at', DateTimeType::class, [
//                'label' => 'Crée le : ',
//                'widget' => 'single_text',
//            ])
//            ->add('is_published')
//            ->add('slug')
            ->add('imageFile', VichImageType::class, [
                'label' => 'Image',
                'required' => false,
                'allow_delete' => false,
                'download_uri' => false,
                'image_uri' => false,
                'asset_helper' => true,
                'constraints' => $options['is_new'] ? [
                    new NotBlank([
                        'message' => 'l\'image est requise.',
                    ])
                ] : [],
            ])

            ->add('pdfFile', VichFileType::class, [
                'label' => 'Programme (PDF)',
                'required' => false,
                'allow_delete' => false,
                'download_uri' => true,
                'download_label' => 'Télécharger le fichier actuel',
                'asset_helper' => true,
                'constraints' => $options['is_new'] ? [
                    new NotBlank([
                        'message' => 'le pdf est requis.',
                    ])
                ] : [],
            ])

            ->add('category', EntityType::class, [
                'label' => 'Categorie',
                'class' => Category::class,
                'choice_label' => 'name',
                'placeholder' => 'Choisissez une categorie',
            ])

            ->add('level', EntityType::class, [
                'label' => 'Niveau',
                'class' => Level::class,
                'choice_label' => 'name',
                'placeholder' => 'Choisissez un niveau',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Course::class,
            'is_new' => false,
        ]);
    }
}

src/Controller/CourseController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use App\Repository\CourseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class CourseController extends AbstractController
{
    public function __construct(private readonly sluggerInterface $slugger)
    {

    }
    #[Route('/courses', name: 'app_courses')]
    public function courses(CourseRepository $repository, Request $request, PaginatorInterface $paginator): Response
    {
        $course = $repository->findBy(
            ['is_published' => true],
        );
        $pagination = $paginator->paginate($course, $request->query->getInt('page', 1), 6);
        return $this->render('course/courses.html.twig', [
            'course' => $pagination,
        ]);
    }

    #[Route('/course/{slug}', name: 'app_course')]
    public function course(string $slug, CourseRepository $repository,CommentRepository $commentRepository, Request $request, Security $security, EntityManagerInterface $manager): Response
    {
        $course = $repository->findOneBy(['slug' => $slug]);

        $comment = new Comment();
        $commentForm = $this->createForm(CommentType::class, $comment);
        $commentForm->handleRequest($request);
        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            $user = $security->getUser();
            if (!$user) {
                return $this->redirectToRoute('app_login');
            }
            else {
                $comment
                    ->setUser($user)
                    ->setSend(false)
                    ->setCourse($course)
                    ->setPublished(false)
                    ->setCreatedAt(new \DateTimeImmutable());
                $manager->persist($comment);
                $manager->flush();
                $this->addFlash(
                    'success',
                    'Votre commentaire à été soumis.'
                );
            }
            return $this->redirectToRoute('app_course', ['slug' => $slug]);
        }
        $user = $security->getUser();
        $userComment = null;
        if ($user) {
            $userComment = $commentRepository->findOneBy(['course' => $course, 'user' => $user]);
        }
        return $this->render('course/course.html.twig', [
            'course' => $course,
            'commentForm' => $commentForm,
            'userComment' => $userComment,
        ]);
    }
}

templates/course/course.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ course.name}} {% endblock %}
{% block body %}
    <section>
        <div class="container mx-auto">
            {#      {% for course in courses %} #}
            <div class="mb-4 border-b border-gray-200 dark:border-gray-700">
                <ul class="flex flex-wrap -mb-px text-sm font-medium text-center" id="default-tab"
                    data-tabs-toggle="#default-tab-content" role="tablist">
                    <li class="me-2" role="presentation">
                        <button class="inline-block p-4 border-b-2 rounded-t-lg" id="profile-tab"
                                data-tabs-target="#profile" type="button" role="tab" aria-controls="profile"
                                aria-selected="false">Profile
                        </button>
                    </li>
                    <li class="me-2" role="presentation">
                        <button class="inline-block p-4 border-b-2 rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300"
                                id="dashboard-tab" data-tabs-target="#dashboard" type="button" role="tab"
                                aria-controls="dashboard" aria-selected="false">Détails
                        </button>
                    </li>
                    <li class="me-2" role="presentation">
                        <button class="inline-block p-4 border-b-2 rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300"
                                id="settings-tab" data-tabs-target="#settings" type="button" role="tab"
                                aria-controls="settings" aria-selected="false">Commentaire
                        </button>
                    </li>
                    <li role="presentation">
                        <button class="inline-block p-4 border-b-2 rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300"
                                id="contacts-tab" data-tabs-target="#contacts" type="button" role="tab"
                                aria-controls="contacts" aria-selected="false">Postez un commentaire
                        </button>
                    </li>
                </ul>
            </div>
            <div id="default-tab-content" class="flex flex-row">
                <div class="hidden p-4 rounded-lg bg-gray-50 dark:bg-gray-800" id="profile" role="tabpanel"
                     aria-labelledby="profile-tab">
                    <h1 class="mb-4 text-4xl">{{ course.name }}</h1>
                    <div class="flex items-center">
                        <img src="{{ asset('images/course/' ~ course.image) }}" alt="" class="w-1/2 h-auto mr-4">
                        <div class="flex-1">
                            <h2 class="text-lg font-semibold">Description</h2>
                            <p class="text-sm text-gray-500 dark:text-gray-400">{{ course.smallDescription }}</p>
                            <h2 class="mt-4">Information</h2>
                            <p class="text-sm text-gray-500 dark:text-gray-400 mt-2">Prix : {{ course.price }} €</p>
                            <p class="text-sm text-gray-500 dark:text-gray-400 mt-2">Durée : {{ course.duration }}</p>
                            <p class="text-sm text-gray-500 dark:text-gray-400 mt-2">Catégorie
                                : {{ course.category.name }}</p>
                            <p class="text-sm text-gray-500 dark:text-gray-400 mt-2">Ajouté le
                                : {{ course.createdAt|date("d/m/Y") }}</p>
                            <p class="text-sm text-gray-500 dark:text-gray-400 mt-4">Niveau :
                                <button data-tooltip-target="tooltip-no-arrow" type="button"
                                        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">{{ course.level.name }}</button>

                            <div id="tooltip-no-arrow" role="tooltip"
                                 class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
                                {{ course.level.prerequisite }}
                            </div>
                            </p>
                        </div>
                    </div>
                </div>
            </div>


            <div class="hidden p-4 rounded-lg bg-gray-50 dark:bg-gray-800" id="dashboard" role="tabpanel"
                 aria-labelledby="dashboard-tab">
                <h2 class="text-2xl m-4">Description complète</h2>
                <p class="text-gray-500 dark:text-gray-400 m-4">{{ course.fullDescription |nl2br }}</p>
                <div class="m-4">
                    <a href="{{ asset('images/program/' ~ course.program) }}" download class="inline-block px-6 py-2 text-white bg-blue-500 rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50"> Télécharger le PDF </a>
                </div>
            </div>
            <div class="hidden p-4 rounded-lg bg-gray-50 dark:bg-gray-800" id="settings" role="tabpanel"
                 aria-labelledby="settings-tab">
                <h2 class="text-2xl mt-4 font-semibold text-gray-800">Commentaires</h2>
                <div class="mt-4 space-y-6">
                    {% for comment in course.comments %}
                    {% if comment.published %}
                        <div class="p-4 bg-white shadow-md rounded-lg">
                            <div class="text-sm text-gray-500 mb-2">
                                <img class="w-12 h-12 rounded-full"
                                     src="{{ asset('images/avatar/' ~ comment.user.image) }}"
                                     alt="{{ comment.user.firstName }}">

                                {{ comment.createdAt | date('d/m/Y') }} - {{ comment.user.firstName }}
                            </div>
                            <p class="text-gray-700 mb-4">{{ comment.content }}</p>
                            <div class="flex space-x-1 text-sm text-gray-500 mb-2">
                                evalutation de {{ comment.user.firstName }} :
                                {% for i in 1..5 %}
                                    {% if i <= comment.assement %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="1.4rem" height="1.4rem"
                                             viewBox="0 0 24 24">
                                            <path fill="#dada10"
                                                  d="m12 18.26l-7.053 3.948l1.575-7.928L.588 8.792l8.027-.952L12 .5l3.385 7.34l8.027.952l-5.934 5.488l1.575 7.928z"/>
                                        </svg>
                                    {% else %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="1.4rem" height="1.4rem"
                                             viewBox="0 0 24 24">
                                            <path fill="black"
                                                  d="m12 18.26l-7.053 3.948l1.575-7.928L.588 8.792l8.027-.952L12 .5l3.385 7.34l8.027.952l-5.934 5.488l1.575 7.928zm0-2.292l4.247 2.377l-.948-4.773l3.573-3.305l-4.833-.573l-2.038-4.419l-2.039 4.42l-4.833.572l3.573 3.305l-.948 4.773z"/>
                                        </svg>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="hidden p-4 rounded-lg bg-gray-50 dark:bg-gray-800" id="contacts" role="tabpanel"
                 aria-labelledby="contacts-tab">
                <div class="mt-10 max-w-2xl mx-auto">
                    {% if app.user %}
                        {% if userComment %}
                            <p>Vous avez déjà posté un commentaire pour cette formation.</p>
                        {% else %}
                            {{ form_start(commentForm) }}
                            {{ form_widget(commentForm) }}
                            <input type="submit" class="inline-block w-full bg-indigo-500 hover:bg-indigo-600 p-4"
                                   value="Envoyer">
                            {{ form_end(commentForm) }}
                        {% endif %}
                    {% else %}
                        <p>Veuillez <a href="{{ path('app_login') }}">vous connecter</a> pour poster un commentaire.
                        </p>
                    {% endif %}
                </div>
            </div>
        </div>
        {#      {% endfor %} #}
    </section>
{% endblock %}

templates/course/courses.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formations{% endblock %}

{% block body %}
    <h1 class="text-4xl text-center m-6">Toutes les formations</h1>
    <main>
        <section>
            <div class="min-h-screen flex flex-col">
                <!-- Contenu principal -->
                <div class="flex-grow flex justify-center items-center">
                    <div class="courses grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                        {% for courses in course %}
                            <div class="max-w-sm bg-white border-[10px] border-gray-200 shadow dark:bg-gray-800 dark:border-gray-700">
                                <img src="{{ asset('images/course/' ~ courses.image) }}" alt="{{ courses.name }}"/>
                                <div class="p-5">
                                    <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ courses.name }}</h2>
                                    <p>Categorie : {{ courses.category.name }}</p>
                                    <p class="mt-4 font-normal text-gray-700 dark:text-gray-400">{{ courses.smallDescription | u.truncate(50, '...', false) }}</p>
                                    <a href="{{ path('app_course', {slug: courses.slug}) }}"
                                       class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 mt-4">
                                        Voir plus
                                        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true"
                                             xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                                  stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                                        </svg>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                <!-- Pagination -->
                <div class="mt-6 flex justify-center">
                    {{ knp_pagination_render(course, 'partials/pagination.html.twig') }}
                </div>
            </div>
        </section>
    </main>
{% endblock %}